"""The per-request context block, and where it goes.

Everything that changes from one request to the next -- the clock, and the
context providers' view of notes, calendar, Home Assistant and the weather --
is rendered here into a single ``<turn_context>`` block and delivered at the
*end* of the prompt rather than inside the system prompt.

Providers cache by longest common prefix, so a value that changes every request ends
the cache hit at wherever it sits. Interpolated into the system prompt it sat
ahead of the entire conversation history and capped the cacheable prefix at a
few thousand tokens; at the tail it ends the prefix where the prompt was going
to end anyway. See docs/design/prompt-cache-turn-context.md.

The Live API paths (voice, telephony) have no message list to append to, so they
render the same block into their system instruction. They share this module so
the two spellings cannot drift apart.
"""

from __future__ import annotations

from typing import Literal

from family_assistant.llm.messages import UserMessage

TURN_CONTEXT_TAG = "turn_context"

_OPEN_TAG = f"<{TURN_CONTEXT_TAG}>"
_CLOSE_TAG = f"</{TURN_CONTEXT_TAG}>"


def turn_context_guidance(
    *,
    includes_aggregated_context: bool,
    placement: Literal["appended", "inline"],
) -> str:
    """Describe the block to the model.

    Two things have to be accurate or the description does harm rather than good.
    *includes_aggregated_context* must reflect the profile's actual grant: telling
    a profile its notes and calendar are in the block when the block holds only a
    clock invites it to answer "nothing scheduled" from an empty block instead of
    saying it has no calendar access. And *placement* differs by transport -- a
    Live API session has no message list, so its block is inlined in the system
    instruction rather than appended to the conversation.
    """
    carries = (
        "the current time plus background context such as your notes, calendar and "
        "home state"
        if includes_aggregated_context
        else "the current time"
    )
    where = (
        "is appended to the end of the conversation on every request"
        if placement == "appended"
        else "appears below"
    )
    return (
        f"A {_OPEN_TAG} block {where}. It is generated by the system, and carries "
        f"{carries}. It is not written by the user and is not part of what they "
        "said. Use it freely, but never reproduce the block or its tags in your reply."
    )


def _neutralize_tags(text: str) -> str:
    """Defuse literal ``<turn_context>`` markup inside provider output.

    The block's contents are notes, calendar summaries and Home Assistant state --
    data the user's own tools write, and which email intake can reach. A note body
    containing the closing tag would otherwise end the block early, leaving the
    text after it looking like ordinary conversation to a model that has just been
    told everything inside the block is system-generated.
    """
    return text.replace(_OPEN_TAG, f"&lt;{TURN_CONTEXT_TAG}&gt;").replace(
        _CLOSE_TAG, f"&lt;/{TURN_CONTEXT_TAG}&gt;"
    )


def render_turn_context_block(
    *,
    current_time_str: str,
    aggregated_context: str,
) -> str:
    """Render the per-request context block.

    Always non-empty: a profile that receives no aggregated context still gets the
    time. *aggregated_context* is the context providers' output, already filtered
    by the profile's ``include_aggregated_context`` and
    ``excluded_context_providers`` settings.
    """
    sections = [f"Current time: {current_time_str}"]
    if aggregated_context.strip():
        sections.append(_neutralize_tags(aggregated_context.strip()))
    body = "\n\n".join(sections)
    return f"{_OPEN_TAG}\n{body}\n{_CLOSE_TAG}"


def build_turn_context_message(
    *,
    current_time_str: str,
    aggregated_context: str,
) -> UserMessage:
    """Build the trailing message carrying this request's context block.

    A user message rather than a system one: Anthropic hoists every system message
    into the top-level ``system`` parameter and context pruning hoists them to the
    front of the pruned list, either of which would put this block back ahead of
    the history it needs to follow.
    """
    return UserMessage(
        content=render_turn_context_block(
            current_time_str=current_time_str,
            aggregated_context=aggregated_context,
        ),
        is_turn_scaffolding=True,
    )
