"""The per-request context block, and where it goes.

Everything that changes from one request to the next -- the clock, and the
context providers' view of notes, calendar, Home Assistant and the weather --
is rendered here into a single ``<turn_context>`` block and delivered at the
*end* of the prompt rather than inside the system prompt.

Providers cache by longest common prefix, so a value that changes every request ends
the cache hit at wherever it sits. Interpolated into the system prompt it sat
ahead of the entire conversation history and capped the cacheable prefix at a
few thousand tokens; at the tail it ends the prefix where the prompt was going
to end anyway. See docs/design/prompt-cache-turn-context.md.

The Live API paths (voice, telephony) have no message list to append to, so they
render the same block into their system instruction. They share this module so
the two spellings cannot drift apart.
"""

from __future__ import annotations

from family_assistant.llm.messages import UserMessage

TURN_CONTEXT_TAG = "turn_context"

SYSTEM_PROMPT_GUIDANCE = (
    f"A <{TURN_CONTEXT_TAG}> block is appended to the end of the conversation on "
    "every request. It is generated by the system for that request and carries the "
    "current time plus background context such as your notes, calendar and home "
    "state. It is not written by the user and is not part of what they said. Use it "
    "freely, but never reproduce the block or its tags in your reply."
)


def render_turn_context_block(
    *,
    current_time_str: str,
    aggregated_context: str,
) -> str:
    """Render the per-request context block, or ``""`` if there is nothing to say.

    *aggregated_context* is the context providers' output, already filtered by the
    profile's ``include_aggregated_context`` and ``excluded_context_providers``
    settings. A profile that receives none still gets the time.
    """
    sections = [f"Current time: {current_time_str}"]
    if aggregated_context.strip():
        sections.append(aggregated_context.strip())
    body = "\n\n".join(sections)
    return f"<{TURN_CONTEXT_TAG}>\n{body}\n</{TURN_CONTEXT_TAG}>"


def build_turn_context_message(
    *,
    current_time_str: str,
    aggregated_context: str,
) -> UserMessage:
    """Build the trailing message carrying this request's context block.

    A user message rather than a system one: Anthropic hoists every system message
    into the top-level ``system`` parameter and context pruning hoists them to the
    front of the pruned list, either of which would put this block back ahead of
    the history it needs to follow.
    """
    return UserMessage(
        content=render_turn_context_block(
            current_time_str=current_time_str,
            aggregated_context=aggregated_context,
        ),
        is_turn_scaffolding=True,
    )
