"""Names of the Gemini computer-use predefined functions.

Kept in a dependency-free module so the Gemini provider client and the
confirmation renderers can reference the action space without importing the
browser/Playwright stack.

This is the action space emitted by Gemini 3.5 models when the computer-use
tool is attached. Every action also carries an ``intent`` string argument
generated by the model.
"""

from __future__ import annotations

COMPUTER_USE_FUNCTION_NAMES: frozenset[str] = frozenset({
    "click",
    "double_click",
    "drag_and_drop",
    "go_back",
    "go_forward",
    "hotkey",
    "key_down",
    "key_up",
    "middle_click",
    "mouse_down",
    "mouse_up",
    "move",
    "navigate",
    "press_key",
    "right_click",
    "scroll",
    "take_screenshot",
    "triple_click",
    "type",
    "wait",
})
