"""Add subconversation_id to message_history

Revision ID: f2a1b3c4d5e6
Revises: 974697dea951
Create Date: 2025-11-07 08:45:00.000000+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2a1b3c4d5e6"
down_revision: str | None = "974697dea951"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_history",
        sa.Column("subconversation_id", sa.String(length=36), nullable=True),
    )
    op.create_index(
        op.f("ix_message_history_subconversation_id"),
        "message_history",
        ["subconversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_history_subconversation_id"), table_name="message_history"
    )
    op.drop_column("message_history", "subconversation_id")
    # ### end Alembic commands ###
