"""Add reasoning content and debug information to message history

Revision ID: a4b677e8e0d1
Revises: a7c55b979906
Create Date: 2025-04-30 17:51:18.546948+10:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4b677e8e0d1"
down_revision: Union[str, None] = "a7c55b979906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_history",
        sa.Column(
            "reasoning_info",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "message_history", sa.Column("error_traceback", sa.Text(), nullable=True)
    )
    op.alter_column(
        "message_history", "content", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message_history", "content", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("message_history", "error_traceback")
    op.drop_column("message_history", "reasoning_info")
    # ### end Alembic commands ###
