"""message history refactoring to separate ID space from telegram message ID, allow storing intermediate messages

Revision ID: d75c672e4c87
Revises: c6dae031c51f
Create Date: 2025-05-04 11:48:55.327902+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd75c672e4c87'
down_revision: Union[str, None] = 'c6dae031c51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_embeddings', 'embedding',
               existing_type=sa.NUMERIC(),
               type_=pgvector.sqlalchemy.vector.VECTOR(),
               existing_nullable=False)
    op.create_index('idx_doc_embeddings_document_chunk', 'document_embeddings', ['document_id', 'chunk_index'], unique=False)
    op.add_column('message_history', sa.Column('internal_id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('message_history', sa.Column('interface_type', sa.String(length=50), nullable=False))
    op.add_column('message_history', sa.Column('conversation_id', sa.String(length=255), nullable=False))
    op.add_column('message_history', sa.Column('interface_message_id', sa.String(length=255), nullable=True))
    op.add_column('message_history', sa.Column('turn_id', sa.String(length=36), nullable=True))
    op.add_column('message_history', sa.Column('thread_root_id', sa.BigInteger(), nullable=True))
    op.add_column('message_history', sa.Column('tool_calls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_message_history_conversation_id'), 'message_history', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_history_interface_message_id'), 'message_history', ['interface_message_id'], unique=False)
    op.create_index(op.f('ix_message_history_interface_type'), 'message_history', ['interface_type'], unique=False)
    op.create_index(op.f('ix_message_history_thread_root_id'), 'message_history', ['thread_root_id'], unique=False)
    op.create_index(op.f('ix_message_history_turn_id'), 'message_history', ['turn_id'], unique=False)
    op.drop_column('message_history', 'tool_calls_info')
    op.drop_column('message_history', 'message_id')
    op.drop_column('message_history', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('chat_id', sa.BIGINT(), nullable=False))
    op.add_column('message_history', sa.Column('message_id', sa.BIGINT(), nullable=False))
    op.add_column('message_history', sa.Column('tool_calls_info', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_message_history_turn_id'), table_name='message_history')
    op.drop_index(op.f('ix_message_history_thread_root_id'), table_name='message_history')
    op.drop_index(op.f('ix_message_history_interface_type'), table_name='message_history')
    op.drop_index(op.f('ix_message_history_interface_message_id'), table_name='message_history')
    op.drop_index(op.f('ix_message_history_conversation_id'), table_name='message_history')
    op.drop_column('message_history', 'tool_calls')
    op.drop_column('message_history', 'thread_root_id')
    op.drop_column('message_history', 'turn_id')
    op.drop_column('message_history', 'interface_message_id')
    op.drop_column('message_history', 'conversation_id')
    op.drop_column('message_history', 'interface_type')
    op.drop_column('message_history', 'internal_id')
    op.drop_index('idx_doc_embeddings_document_chunk', table_name='document_embeddings')
    op.alter_column('document_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
