"""Add user_id to message_history

Revision ID: 974697dea951
Revises: a7c55b979906
Create Date: 2025-10-17 21:06:36.032882+11:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974697dea951"
down_revision: str | None = "a7c55b979906"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_history", sa.Column("user_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_message_history_user_id"), "message_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_history_user_id"), table_name="message_history")
    op.drop_column("message_history", "user_id")
    # ### end Alembic commands ###
