"""Add foreign key constraint for message_id in attachment_metadata

Revision ID: f2e47092d2be
Revises: 9ead44a79229
Create Date: 2025-09-24 22:04:16.041571+10:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2e47092d2be"
down_revision: str | None = "9ead44a79229"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    dialect_name = op.get_context().dialect.name

    if dialect_name == "postgresql":
        # PostgreSQL: Can alter column type and add foreign key directly
        op.alter_column(
            "attachment_metadata",
            "metadata",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.JSON(),
            existing_nullable=True,
        )
        op.create_foreign_key(
            "fk_attachment_metadata_message_id",
            "attachment_metadata",
            "message_history",
            ["message_id"],
            ["internal_id"],
        )
    elif dialect_name == "sqlite":
        # SQLite: Use batch mode to recreate table with foreign key
        with op.batch_alter_table("attachment_metadata", schema=None) as batch_op:
            batch_op.create_foreign_key(
                "fk_attachment_metadata_message_id",
                "message_history",
                ["message_id"],
                ["internal_id"],
            )
    else:
        # Other dialects: Assume basic foreign key support
        op.create_foreign_key(
            "fk_attachment_metadata_message_id",
            "attachment_metadata",
            "message_history",
            ["message_id"],
            ["internal_id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    dialect_name = op.get_context().dialect.name

    if dialect_name == "postgresql":
        # PostgreSQL: Can drop foreign key and alter column type directly
        op.drop_constraint(
            "fk_attachment_metadata_message_id",
            "attachment_metadata",
            type_="foreignkey",
        )
        op.alter_column(
            "attachment_metadata",
            "metadata",
            existing_type=sa.JSON(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )
    elif dialect_name == "sqlite":
        # SQLite: Use batch mode to recreate table without foreign key
        with op.batch_alter_table("attachment_metadata", schema=None) as batch_op:
            batch_op.drop_constraint(
                "fk_attachment_metadata_message_id", type_="foreignkey"
            )
    else:
        # Other dialects: Assume basic foreign key drop support
        op.drop_constraint(
            "fk_attachment_metadata_message_id",
            "attachment_metadata",
            type_="foreignkey",
        )
    # ### end Alembic commands ###
