"""Missing from prod db

Revision ID: 93331cd6ffee
Revises: 91da85378f27
Create Date: 2025-05-20 07:46:59.477555+10:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93331cd6ffee"
down_revision: str | None = "91da85378f27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_embeddings",
        sa.Column(
            "embedding_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_embeddings", "embedding_metadata")
    # ### end Alembic commands ###
