"""Add tool_name column to message_history table

Revision ID: db7825a36aae
Revises: 3914471709b5
Create Date: 2025-09-22 07:42:17.575064+10:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db7825a36aae"
down_revision: str | None = "3914471709b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_history", sa.Column("tool_name", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_message_history_tool_name"),
        "message_history",
        ["tool_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_history_tool_name"), table_name="message_history")
    op.drop_column("message_history", "tool_name")
    # ### end Alembic commands ###
