"""Initial schema

Revision ID: 6daf0237b0ba
Revises:
Create Date: 2025-08-25 12:28:30.984821+10:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6daf0237b0ba"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_identifier", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("hashed_token", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prefix"),
    )
    op.create_index(
        op.f("ix_api_tokens_hashed_token"), "api_tokens", ["hashed_token"], unique=True
    )
    op.create_index(op.f("ix_api_tokens_id"), "api_tokens", ["id"], unique=False)
    op.create_index(
        op.f("ix_api_tokens_user_identifier"),
        "api_tokens",
        ["user_identifier"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "doc_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_index(
        "idx_documents_doc_metadata",
        "documents",
        ["doc_metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_documents_source_type"), "documents", ["source_type"], unique=False
    )
    op.create_table(
        "error_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("logger_name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("exception_message", sa.Text(), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("module", sa.String(length=255), nullable=True),
        sa.Column("function_name", sa.String(length=255), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_error_logs_level"), "error_logs", ["level"], unique=False)
    op.create_index(
        op.f("ix_error_logs_logger_name"), "error_logs", ["logger_name"], unique=False
    )
    op.create_index(
        op.f("ix_error_logs_module"), "error_logs", ["module"], unique=False
    )
    op.create_index(
        op.f("ix_error_logs_timestamp"), "error_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "event_listeners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_id",
            sa.Enum("home_assistant", "indexing", "webhook", name="eventsourcetype"),
            nullable=False,
        ),
        sa.Column(
            "match_conditions",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "action_type",
            sa.Enum("wake_llm", "script", name="eventactiontype"),
            server_default="wake_llm",
            nullable=False,
        ),
        sa.Column(
            "action_config",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("condition_script", sa.Text(), nullable=True),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column(
            "interface_type",
            sa.Enum("telegram", "web", "email", name="interfacetype"),
            server_default="telegram",
            nullable=False,
        ),
        sa.Column("one_time", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("daily_executions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("daily_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_execution_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "conversation_id", name="uq_name_conversation"),
    )
    op.create_index(
        "idx_conversation",
        "event_listeners",
        ["conversation_id", "enabled"],
        unique=False,
    )
    op.create_index(
        "idx_source_enabled", "event_listeners", ["source_id", "enabled"], unique=False
    )
    op.create_index(
        op.f("ix_event_listeners_conversation_id"),
        "event_listeners",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_listeners_source_id"),
        "event_listeners",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "message_history",
        sa.Column("internal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_type", sa.String(length=50), nullable=False),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("interface_message_id", sa.String(length=255), nullable=True),
        sa.Column("turn_id", sa.String(length=36), nullable=True),
        sa.Column("thread_root_id", sa.BigInteger(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "tool_calls",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "reasoning_info",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("tool_call_id", sa.String(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("processing_profile_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("internal_id"),
    )
    op.create_index(
        op.f("ix_message_history_conversation_id"),
        "message_history",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_interface_message_id"),
        "message_history",
        ["interface_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_interface_type"),
        "message_history",
        ["interface_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_processing_profile_id"),
        "message_history",
        ["processing_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_thread_root_id"),
        "message_history",
        ["thread_root_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_timestamp"),
        "message_history",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_tool_call_id"),
        "message_history",
        ["tool_call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_history_turn_id"), "message_history", ["turn_id"], unique=False
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "include_in_prompt", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_title"), "notes", ["title"], unique=True)
    op.create_table(
        "received_emails",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("message_id_header", sa.Text(), nullable=False),
        sa.Column("sender_address", sa.Text(), nullable=True),
        sa.Column("from_header", sa.Text(), nullable=True),
        sa.Column("recipient_address", sa.Text(), nullable=True),
        sa.Column("to_header", sa.Text(), nullable=True),
        sa.Column("cc_header", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("body_plain", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("stripped_text", sa.Text(), nullable=True),
        sa.Column("stripped_html", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("email_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "headers_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "attachment_info",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("mailgun_timestamp", sa.Text(), nullable=True),
        sa.Column("mailgun_token", sa.Text(), nullable=True),
        sa.Column("indexing_task_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_received_emails_email_date"),
        "received_emails",
        ["email_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_received_emails_indexing_task_id"),
        "received_emails",
        ["indexing_task_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_received_emails_message_id_header"),
        "received_emails",
        ["message_id_header"],
        unique=True,
    )
    op.create_index(
        op.f("ix_received_emails_received_at"),
        "received_emails",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_received_emails_recipient_address"),
        "received_emails",
        ["recipient_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_received_emails_sender_address"),
        "received_emails",
        ["sender_address"],
        unique=False,
    )
    op.create_table(
        "recent_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=100), nullable=False),
        sa.Column(
            "source_id",
            sa.Enum("home_assistant", "indexing", "webhook", name="eventsourcetype"),
            nullable=False,
        ),
        sa.Column(
            "event_data",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "triggered_listener_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index("idx_created", "recent_events", ["created_at"], unique=False)
    op.create_index(
        "idx_source_time", "recent_events", ["source_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_recent_events_source_id"), "recent_events", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_recent_events_timestamp"), "recent_events", ["timestamp"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("locked_by", sa.String(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("recurrence_rule", sa.String(), nullable=True),
        sa.Column("original_task_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_scheduled_at"), "tasks", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_task_id"), "tasks", ["task_id"], unique=True)
    op.create_index(op.f("ix_tasks_task_type"), "tasks", ["task_type"], unique=False)

    # PostgreSQL-specific vector tables
    if op.get_bind().dialect.name == "postgresql":
        # Create pgvector extension before creating tables that use VECTOR type
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

        import pgvector.sqlalchemy

        op.create_table(
            "document_embeddings",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("document_id", sa.Integer(), nullable=False),
            sa.Column("chunk_index", sa.Integer(), nullable=False),
            sa.Column("embedding_type", sa.String(length=50), nullable=False),
            sa.Column("content", sa.Text(), nullable=True),
            sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
            sa.Column("embedding_model", sa.String(length=100), nullable=False),
            sa.Column("content_hash", sa.Text(), nullable=True),
            sa.Column(
                "added_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column(
                "embedding_metadata",
                sa.JSON().with_variant(
                    postgresql.JSONB(astext_type=sa.Text()), "postgresql"
                ),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["document_id"], ["documents.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("document_id", "chunk_index", "embedding_type"),
        )
        op.create_index(
            "idx_doc_embeddings_document_chunk",
            "document_embeddings",
            ["document_id", "chunk_index"],
            unique=False,
        )
        op.create_index(
            "idx_doc_embeddings_type_model",
            "document_embeddings",
            ["embedding_type", "embedding_model"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop PostgreSQL-specific vector tables first
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index("idx_doc_embeddings_type_model", table_name="document_embeddings")
        op.drop_index(
            "idx_doc_embeddings_document_chunk", table_name="document_embeddings"
        )
        op.drop_table("document_embeddings")
    op.drop_index(op.f("ix_tasks_task_type"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_scheduled_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_recent_events_timestamp"), table_name="recent_events")
    op.drop_index(op.f("ix_recent_events_source_id"), table_name="recent_events")
    op.drop_index("idx_source_time", table_name="recent_events")
    op.drop_index("idx_created", table_name="recent_events")
    op.drop_table("recent_events")
    op.drop_index(
        op.f("ix_received_emails_sender_address"), table_name="received_emails"
    )
    op.drop_index(
        op.f("ix_received_emails_recipient_address"), table_name="received_emails"
    )
    op.drop_index(op.f("ix_received_emails_received_at"), table_name="received_emails")
    op.drop_index(
        op.f("ix_received_emails_message_id_header"), table_name="received_emails"
    )
    op.drop_index(
        op.f("ix_received_emails_indexing_task_id"), table_name="received_emails"
    )
    op.drop_index(op.f("ix_received_emails_email_date"), table_name="received_emails")
    op.drop_table("received_emails")
    op.drop_index(op.f("ix_notes_title"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_message_history_turn_id"), table_name="message_history")
    op.drop_index(op.f("ix_message_history_tool_call_id"), table_name="message_history")
    op.drop_index(op.f("ix_message_history_timestamp"), table_name="message_history")
    op.drop_index(
        op.f("ix_message_history_thread_root_id"), table_name="message_history"
    )
    op.drop_index(
        op.f("ix_message_history_processing_profile_id"), table_name="message_history"
    )
    op.drop_index(
        op.f("ix_message_history_interface_type"), table_name="message_history"
    )
    op.drop_index(
        op.f("ix_message_history_interface_message_id"), table_name="message_history"
    )
    op.drop_index(
        op.f("ix_message_history_conversation_id"), table_name="message_history"
    )
    op.drop_table("message_history")
    op.drop_index(op.f("ix_event_listeners_source_id"), table_name="event_listeners")
    op.drop_index(
        op.f("ix_event_listeners_conversation_id"), table_name="event_listeners"
    )
    op.drop_index("idx_source_enabled", table_name="event_listeners")
    op.drop_index("idx_conversation", table_name="event_listeners")
    op.drop_table("event_listeners")
    op.drop_index(op.f("ix_error_logs_timestamp"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_module"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_logger_name"), table_name="error_logs")
    op.drop_index(op.f("ix_error_logs_level"), table_name="error_logs")
    op.drop_table("error_logs")
    op.drop_index(op.f("ix_documents_source_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_index(
        "idx_documents_doc_metadata", table_name="documents", postgresql_using="gin"
    )
    op.drop_table("documents")
    op.drop_index(op.f("ix_api_tokens_user_identifier"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_hashed_token"), table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
