"""Initial revision

Revision ID: a7c55b979906
Revises: 
Create Date: 2025-04-30 15:32:39.422829+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7c55b979906'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().engine.name == 'mysql':
        op.create_index('idx_doc_embeddings_gemini_1536_hnsw_cos', 'document_embeddings', [sa.literal_column('(embedding::vector(1536)) vector_cosine_ops')], unique=False, postgresql_using='hnsw', postgresql_where=sa.text("embedding_model = 'gemini-exp-03-07'"), postgresql_with={'m': 16, 'ef_construction': 64})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_embeddings_gemini_1536_hnsw_cos', table_name='document_embeddings', postgresql_using='hnsw', postgresql_where=sa.text("embedding_model = 'gemini-exp-03-07'"), postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_table('credentials',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('integration_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'integration_name', name='credentials_pkey')
    )
    op.create_table('context_data',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('data_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding_openai_ada002', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'dataset', 'data_id', name='context_data_pkey')
    )
    # ### end Alembic commands ###
