"""More lingering changes

Revision ID: 3a3d3a70f182
Revises: 649d1365dccc
Create Date: 2025-05-05 23:31:00.475544+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a3d3a70f182'
down_revision: Union[str, None] = '649d1365dccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_doc_embeddings_gemini_1536_hnsw_cos', 'document_embeddings', [sa.literal_column('(embedding::vector(1536)) vector_cosine_ops')], unique=False, postgresql_using='hnsw', postgresql_where=sa.text("embedding_model = 'gemini-exp-03-07'"), postgresql_with={'m': 16, 'ef_construction': 64})
    op.add_column('message_history', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.add_column('message_history', sa.Column('message_id', sa.BigInteger(), nullable=False))
    op.add_column('message_history', sa.Column('tool_calls_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_index('ix_message_history_conversation_id', table_name='message_history')
    op.drop_index('ix_message_history_interface_message_id', table_name='message_history')
    op.drop_index('ix_message_history_interface_type', table_name='message_history')
    op.drop_index('ix_message_history_thread_root_id', table_name='message_history')
    op.drop_index('ix_message_history_tool_call_id', table_name='message_history')
    op.drop_index('ix_message_history_turn_id', table_name='message_history')
    op.drop_column('message_history', 'interface_type')
    op.drop_column('message_history', 'thread_root_id')
    op.drop_column('message_history', 'turn_id')
    op.drop_column('message_history', 'internal_id')
    op.drop_column('message_history', 'interface_message_id')
    op.drop_column('message_history', 'tool_calls')
    op.drop_column('message_history', 'tool_call_id')
    op.drop_column('message_history', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('conversation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('message_history', sa.Column('tool_call_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('message_history', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('message_history', sa.Column('interface_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('message_history', sa.Column('internal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message_history', sa.Column('turn_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('message_history', sa.Column('thread_root_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('message_history', sa.Column('interface_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_message_history_turn_id', 'message_history', ['turn_id'], unique=False)
    op.create_index('ix_message_history_tool_call_id', 'message_history', ['tool_call_id'], unique=False)
    op.create_index('ix_message_history_thread_root_id', 'message_history', ['thread_root_id'], unique=False)
    op.create_index('ix_message_history_interface_type', 'message_history', ['interface_type'], unique=False)
    op.create_index('ix_message_history_interface_message_id', 'message_history', ['interface_message_id'], unique=False)
    op.create_index('ix_message_history_conversation_id', 'message_history', ['conversation_id'], unique=False)
    op.drop_column('message_history', 'tool_calls_info')
    op.drop_column('message_history', 'message_id')
    op.drop_column('message_history', 'chat_id')
    op.drop_index('idx_doc_embeddings_gemini_1536_hnsw_cos', table_name='document_embeddings', postgresql_using='hnsw', postgresql_where=sa.text("embedding_model = 'gemini-exp-03-07'"), postgresql_with={'m': 16, 'ef_construction': 64})
    # ### end Alembic commands ###
