"""add_error_logs_table

Revision ID: d93343aecc37
Revises: 8c4cf2ceddd1
Create Date: 2025-06-12 15:49:50.920526+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93343aecc37'
down_revision: Union[str, None] = '8c4cf2ceddd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('logger_name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_level'), 'error_logs', ['level'], unique=False)
    op.create_index(op.f('ix_error_logs_logger_name'), 'error_logs', ['logger_name'], unique=False)
    op.create_index(op.f('ix_error_logs_module'), 'error_logs', ['module'], unique=False)
    op.create_index(op.f('ix_error_logs_timestamp'), 'error_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_logs_timestamp'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_module'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_logger_name'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_level'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
