"""Add tool call IDs to message history database

Revision ID: c6dae031c51f
Revises: a4b677e8e0d1
Create Date: 2025-05-03 22:56:53.635078+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6dae031c51f'
down_revision: Union[str, None] = 'a4b677e8e0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('tool_call_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_message_history_tool_call_id'), 'message_history', ['tool_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_history_tool_call_id'), table_name='message_history')
    op.drop_column('message_history', 'tool_call_id')
    # ### end Alembic commands ###
