"""Add event listener system tables

Revision ID: 8c4cf2ceddd1
Revises: dda18702319b
Create Date: 2025-06-10 14:30:19.625455+10:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import func

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c4cf2ceddd1"
down_revision: str | None = "dda18702319b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_listeners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_id",
            sa.Enum("home_assistant", "indexing", "webhook", name="eventsourcetype"),
            nullable=False,
        ),
        sa.Column(
            "match_conditions",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "action_type",
            sa.Enum("wake_llm", name="eventactiontype"),
            server_default="wake_llm",
            nullable=False,
        ),
        sa.Column(
            "action_config",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column(
            "interface_type",
            sa.Enum("telegram", "web", "email", name="interfacetype"),
            server_default="telegram",
            nullable=False,
        ),
        sa.Column("one_time", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=func.now(),  # pylint: disable=not-callable
            nullable=False,
        ),
        sa.Column("daily_executions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("daily_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_execution_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "conversation_id", name="uq_name_conversation"),
    )
    op.create_index(
        "idx_conversation",
        "event_listeners",
        ["conversation_id", "enabled"],
        unique=False,
    )
    op.create_index(
        "idx_source_enabled", "event_listeners", ["source_id", "enabled"], unique=False
    )
    op.create_index(
        op.f("ix_event_listeners_conversation_id"),
        "event_listeners",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_listeners_source_id"),
        "event_listeners",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "recent_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=100), nullable=False),
        sa.Column(
            "source_id",
            sa.Enum("home_assistant", "indexing", "webhook", name="eventsourcetype"),
            nullable=False,
        ),
        sa.Column(
            "event_data",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "triggered_listener_ids",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=func.now(),  # pylint: disable=not-callable
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index("idx_created", "recent_events", ["created_at"], unique=False)
    op.create_index(
        "idx_source_time", "recent_events", ["source_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_recent_events_source_id"), "recent_events", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_recent_events_timestamp"), "recent_events", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recent_events_timestamp"), table_name="recent_events")
    op.drop_index(op.f("ix_recent_events_source_id"), table_name="recent_events")
    op.drop_index("idx_source_time", table_name="recent_events")
    op.drop_index("idx_created", table_name="recent_events")
    op.drop_table("recent_events")
    op.drop_index(op.f("ix_event_listeners_source_id"), table_name="event_listeners")
    op.drop_index(
        op.f("ix_event_listeners_conversation_id"), table_name="event_listeners"
    )
    op.drop_index("idx_source_enabled", table_name="event_listeners")
    op.drop_index("idx_conversation", table_name="event_listeners")
    op.drop_table("event_listeners")
    # ### end Alembic commands ###
