"""Add processing profile to message history table

Revision ID: 717b6a577405
Revises: 93331cd6ffee
Create Date: 2025-05-29 08:58:18.501210+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717b6a577405'
down_revision: Union[str, None] = '93331cd6ffee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('processing_profile_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_message_history_processing_profile_id'), 'message_history', ['processing_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_history_processing_profile_id'), table_name='message_history')
    op.drop_column('message_history', 'processing_profile_id')
    # ### end Alembic commands ###
