"""Lingering changes

Revision ID: 649d1365dccc
Revises: d75c672e4c87
Create Date: 2025-05-05 22:56:12.046939+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649d1365dccc'
down_revision: Union[str, None] = 'd75c672e4c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_embeddings_gemini_1536_hnsw_cos', table_name='document_embeddings', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((embedding_model)::text = 'gemini-exp-03-07'::text)")
    op.alter_column('message_history', 'internal_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_history', 'internal_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_doc_embeddings_gemini_1536_hnsw_cos', 'document_embeddings', [sa.literal_column('(embedding::vector(1536))')], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((embedding_model)::text = 'gemini-exp-03-07'::text)")
    # ### end Alembic commands ###
