"""Add attachments column to message history

Revision ID: df4c339d1045
Revises: 5c039369c3d7
Create Date: 2025-08-18 20:34:00.709415+10:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df4c339d1045"
down_revision: str | None = "6daf0237b0ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_history",
        sa.Column(
            "attachments",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message_history", "attachments")
    # ### end Alembic commands ###
