#!/usr/bin/env python3
"""Prepare minimally anonymized test data from production tool calls."""

import json
import re
from typing import Any


def minimal_anonymize(data: Any) -> Any:
    """Minimally anonymize data - just names and locations."""
    if isinstance(data, str):
        # Replace email addresses
        data = re.sub(r"[\w\.-]+@[\w\.-]+\.\w+", "user@example.com", data)

        # Replace specific personal names with generic ones
        replacements = {
            # Add actual names from the data if needed
            "Andrew": "Alex",
            "Teija": "Taylor",
            "Garrett": "Smith",
            # Location anonymization
            "Redmond": "Anytown",
            "Seattle": "BigCity",
            "Washington": "State",
        }

        for old, new in replacements.items():
            data = re.sub(rf"\b{old}\b", new, data, flags=re.IGNORECASE)

        return data

    elif isinstance(data, dict):
        return {k: minimal_anonymize(v) for k, v in data.items()}

    elif isinstance(data, list):
        return [minimal_anonymize(item) for item in data]

    return data


def prepare_test_cases() -> dict[str, list[dict[str, Any]]]:
    """Prepare test cases grouped by tool type."""
    with open("tool_calls_test_data.json") as f:
        raw_data = json.load(f)

    # Group by tool type
    test_cases_by_tool = {}

    for record in raw_data:
        if not record.get("tool_calls"):
            continue

        for call in record["tool_calls"]:
            tool_name = call["function"]["name"]

            # Find matching response
            response = None
            if record.get("tool_responses"):
                for resp in record["tool_responses"]:
                    if resp["tool_call_id"] == call["id"]:
                        response = resp
                        break

            if response:  # Only include calls with responses
                test_case = {
                    "tool_call": minimal_anonymize(call),
                    "tool_response": minimal_anonymize(response),
                    "timestamp": record["timestamp"],
                }

                if tool_name not in test_cases_by_tool:
                    test_cases_by_tool[tool_name] = []

                test_cases_by_tool[tool_name].append(test_case)

    return test_cases_by_tool


def main() -> None:
    test_cases = prepare_test_cases()

    # Stats
    print(f"Prepared test cases for {len(test_cases)} tools:")
    for tool, cases in sorted(test_cases.items()):
        print(f"  {tool}: {len(cases)} test cases")

    # Save to test data file
    output_path = "frontend/src/test/toolTestData.js"
    with open(output_path, "w") as f:
        f.write("// Minimally anonymized test data from production\n")
        f.write("// Generated by scripts/prepare_test_data.py\n\n")
        f.write("export const toolTestCases = ")
        f.write(json.dumps(test_cases, indent=2))
        f.write(";\n")

    print(f"\nTest data saved to {output_path}")


if __name__ == "__main__":
    main()
