name: 'Image Smoke Test'
description: 'Builds the production image and verifies it starts correctly'
inputs:
  image-tag:
    description: 'Tag to use for the local image'
    required: true
    default: 'smoke-test'
  registry:
    description: 'Docker registry for caching'
    required: true
  image-prefix:
    description: 'Image prefix for caching'
    required: true
  port:
    description: 'Port to expose'
    required: false
    default: '8000'
  health-path:
    description: 'Path for health check'
    required: false
    default: '/health'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and load local image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: false
        load: true
        tags: family-assistant:${{ inputs.image-tag }}
        cache-from: |
          type=gha
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image-prefix }}:main
          type=registry,ref=${{ inputs.registry }}/${{ inputs.image-prefix }}:buildcache
        cache-to: type=gha,mode=max

    - name: Run smoke test script
      shell: bash
      run: |
        chmod +x scripts/container-smoke-test.sh
        ./scripts/container-smoke-test.sh family-assistant:${{ inputs.image-tag }} ${{ inputs.port }} ${{ inputs.health-path }}
